import streamlit as st
import pandas as pd
import json
import os
import main

st.set_page_config(page_title="Vulnity — Security Orchestrator",
                   layout="wide")
st.title("Automated Security Scanner & AI Patch Advisor")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

RESULTS_PATH = "/app/shared/last_scan.json"


def save_results(ranked, patches):
    """Persist results to disk so a browser refresh can reload them."""
    try:
        with open(RESULTS_PATH, "w") as f:
            json.dump({"ranked": ranked, "patches": patches},
                      f, indent=2, default=str)
    except Exception as e:
        st.warning(f"Could not save results to disk: {e}")


def load_results():
    """Load the most recent scan results from disk (if they exist)."""
    if not os.path.exists(RESULTS_PATH):
        return [], []
    try:
        with open(RESULTS_PATH) as f:
            data = json.load(f)
        return data.get("ranked", []), data.get("patches", [])
    except Exception:
        return [], []


def _flatten_ranked(ranked: list) -> pd.DataFrame:
    rows = []
    for v in ranked:
        breakdown = v.get("score_breakdown", {})
        rows.append({
            "Rank"          : v.get("rank", ""),
            "Score"         : round(v.get("priority_score", 0), 1),
            "Severity"      : v.get("severity", ""),
            "Category"      : v.get("category", ""),
            "Name"          : v.get("name", ""),
            "CVE"           : v.get("cve", ""),
            "CWE"           : v.get("cwe", ""),
            "Tools"         : ", ".join(v.get("source_tools", [])),
            "Location"      : v.get("file") or v.get("endpoint") or "",
            "KEV"           : "✅" if v.get("is_kev") else "",
            "CVSS"          : v.get("cvss_score", ""),
            "EPSS"          : v.get("epss_score", ""),
            "Base Severity" : breakdown.get("base_severity", ""),
            "Exploit Bonus" : breakdown.get("exploit_bonus", ""),
            "Corroboration" : breakdown.get("corroboration_bonus", ""),
            "CVSS Bonus"    : breakdown.get("cvss_bonus", ""),
            "EPSS Bonus"    : breakdown.get("epss_bonus", ""),
            "KEV Bonus"     : breakdown.get("kev_bonus", ""),
        })
    return pd.DataFrame(rows)


def _severity_color(severity: str) -> str:
    return {
        "CRITICAL": "🔴",
        "HIGH"    : "🟠",
        "MEDIUM"  : "🟡",
        "LOW"     : "🟢",
        "INFO"    : "⚪",
    }.get(severity.upper() if severity else "", "⚪")


def _verdict_badge(verdict: str) -> str:
    return {
        "pass"      : "✅",
        "fail"      : "⚠️",
        "unverified": "❔",
    }.get((verdict or "").lower(), "❔")


def show_results(ranked_vulns, ai_patches):
    """Render results tabs — called from session state so it survives reruns."""
    st.success(f"Found **{len(ranked_vulns)}** unique findings "
               f"after deduplication.")

    tab1, tab2, tab3 = st.tabs([
        "Ranked Findings",
        "AI Patch Suggestions",
        "Score Breakdown",
    ])

    with tab1:
        st.subheader("Prioritized Vulnerability Findings")

        severities = ["ALL"] + sorted(set(
            v.get("severity", "") for v in ranked_vulns))
        sel_sev = st.selectbox("Filter by severity", severities,
                               key="sev_filter")

        filtered = (ranked_vulns if sel_sev == "ALL"
                    else [v for v in ranked_vulns
                          if v.get("severity") == sel_sev])

        df = _flatten_ranked(filtered)
        st.dataframe(df, use_container_width=True, hide_index=True)

        st.download_button(
            label="⬇ Download ranked findings (JSON)",
            data=json.dumps(ranked_vulns, indent=2, default=str),
            file_name="ranked_findings.json",
            mime="application/json",
            key="dl_ranked",
        )

    with tab2:
        st.subheader("AI-Generated Patch Suggestions")
        st.caption("Patches generated by DeepSeek-Coder 6.7B "
                   "for the top 3 highest-risk findings.")

        if not ai_patches:
            st.write("No patch suggestions generated.")
        else:
            for i, patch_data in enumerate(ai_patches):
                sev     = patch_data.get("severity", "")
                score   = patch_data.get("score", 0)
                icon    = _severity_color(sev)
                verdict = patch_data.get("verdict", "unverified")
                v_icon  = _verdict_badge(verdict)

                with st.expander(
                    f"{icon} [{sev}] {patch_data['name']} "
                    f"— Score: {score:.1f} — {v_icon} {verdict}",
                    key=f"patch_exp_{i}",
                ):
                    if verdict == "fail":
                        st.warning(
                            "This patch was flagged by the judge model and "
                            "may not fully resolve the vulnerability — "
                            "review before applying."
                        )
                    reason = patch_data.get("verdict_reason", "")
                    if reason:
                        st.caption(f"Judge: {reason}")
                    st.markdown(patch_data["patch"])

    with tab3:
        st.subheader("Score Component Breakdown")
        st.caption("Shows how each scoring signal contributed "
                   "to the final priority score.")

        if ranked_vulns:
            top_n = st.slider("Show top N findings", 3, 20,
                              min(10, len(ranked_vulns)),
                              key="top_n_slider")
            df_full = _flatten_ranked(ranked_vulns[:top_n])

            score_cols = [
                "Rank", "Name", "Score", "Base Severity",
                "CVSS Bonus", "EPSS Bonus", "KEV Bonus",
                "Exploit Bonus", "Corroboration",
            ]
            st.dataframe(
                df_full[score_cols],
                use_container_width=True,
                hide_index=True,
            )


# ---------------------------------------------------------------------------
# Session state initialization — must come before any widget rendering
# ---------------------------------------------------------------------------
if "ranked_vulns" not in st.session_state:
    st.session_state.ranked_vulns = []
if "ai_patches" not in st.session_state:
    st.session_state.ai_patches = []
if "scan_running" not in st.session_state:
    st.session_state.scan_running = False

# ---------------------------------------------------------------------------
# Sidebar — Configuration
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("Configuration")
    target_input = st.text_input(
        "Target URL", value="http://juice-shop:3000")
    repo_input = st.text_input(
        "Repository URL",
        value="https://github.com/juice-shop/juice-shop")

    run_btn = st.button(
        "▶ Start Full Scan",
        use_container_width=True,
        disabled=st.session_state.scan_running,   # grey out during scan
    )
    load_btn = st.button(
        "  Load Previous Results",
        use_container_width=True,
        disabled=st.session_state.scan_running,
    )

    st.divider()
    st.caption("Scanners: SonarQube · ZAP · Trivy · Nuclei · SQLMap · Metasploit")
    st.caption("LLM: DeepSeek-Coder 6.7B via Ollama")

# ---------------------------------------------------------------------------
# Load previous results
# ---------------------------------------------------------------------------
if load_btn:
    ranked, patches = load_results()
    if ranked:
        st.session_state.ranked_vulns = ranked
        st.session_state.ai_patches   = patches
        st.info("  Loaded previous scan results from disk.")
    else:
        st.warning("No saved results found at /app/shared/last_scan.json")

# ---------------------------------------------------------------------------
# Run new scan
# ---------------------------------------------------------------------------
if run_btn:
    st.session_state.scan_running = True
    st.info(f"Scan initiated against **{target_input}**. "
            f"This may take 15–30 minutes.")

    with st.status("Running security pipeline...",
                   expanded=True) as status_box:
        try:
            st.write(" Starting SAST, SCA, DAST, and Pentest scans...")
            st.write("SonarQube, ZAP, Trivy, Nuclei, SQLMap, "
                     "Metasploit running in parallel containers...")
            st.write(" LLM patch generation will run after scanning...")

            ranked_vulns, ai_patches = main.run_all(target_input, repo_input)

            # Persist to session state
            st.session_state.ranked_vulns = ranked_vulns
            st.session_state.ai_patches   = ai_patches

            # Persist to disk so browser refresh keeps results
            save_results(ranked_vulns, ai_patches)

            status_box.update(label="✅ Scan complete!",
                              state="complete", expanded=False)

        except Exception as e:
            status_box.update(label="❌ Scan failed",
                              state="error", expanded=True)
            st.error(f"Pipeline error: {e}")
            st.exception(e)
        finally:
            # Always release the lock, even on failure
            st.session_state.scan_running = False

# ---------------------------------------------------------------------------
# Display results — rendered from session state, survives ALL widget clicks
# ---------------------------------------------------------------------------
if st.session_state.ranked_vulns:
    show_results(st.session_state.ranked_vulns, st.session_state.ai_patches)
elif not st.session_state.scan_running:
    st.info("Configure your target and click 'Start Full Scan' to begin, "
            "or load a previous scan with '  Load Previous Results'.")